repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^DocTest/
      - id: ruff-format
        files: ^DocTest/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^(DocTest|utest)/.*\.py$
      - id: end-of-file-fixer
        files: ^(DocTest|utest)/.*\.py$
      - id: check-yaml
      - id: check-merge-conflict
