"""End-to-end fixtures: a real served dashboard + real robot runs.

The server is `doctest-dashboard serve` (uvicorn subprocess) with the built
frontend; test data is generated by executing the actual DocTest library
under Robot Framework into a session workspace that is the server's
configured root. Nothing is mocked.
"""

import socket
import subprocess
import sys
import time
from pathlib import Path

import httpx
import pytest


def _free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


@pytest.fixture(scope="session")
def workspace(tmp_path_factory) -> Path:
    return tmp_path_factory.mktemp("e2e_workspace")


def _start_server(workspace: Path):
    port = _free_port()
    process = subprocess.Popen(
        [sys.executable, "-m", "doctest_dashboard.cli",
         "--data-dir", str(workspace / ".dashboard"),
         "serve", "--port", str(port), "--root", str(workspace)],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    url = f"http://127.0.0.1:{port}"
    for _ in range(100):
        try:
            if httpx.get(f"{url}/api/health", timeout=1).status_code == 200:
                return process, url
        except httpx.HTTPError:
            time.sleep(0.2)
    output = process.stdout.read().decode(errors="replace") if process.stdout else ""
    raise RuntimeError(f"Server did not start:\n{output}")


@pytest.fixture(scope="session")
def server_url(workspace):
    process, url = _start_server(workspace)
    try:
        yield url
    finally:
        process.terminate()
        process.wait(timeout=10)


@pytest.fixture
def fresh_server_url(tmp_path):
    """A server with an empty database — for first-run/onboarding journeys."""
    process, url = _start_server(tmp_path)
    try:
        yield url
    finally:
        process.terminate()
        process.wait(timeout=10)


@pytest.fixture
def api(server_url):
    with httpx.Client(base_url=server_url, timeout=180) as client:
        yield client
