name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/manykarim/robotframework-doctestlibrary/rf-doctest:$(date +%s) --tag ghcr.io/manykarim/robotframework-doctestlibrary/rf-doctest:latest
    - name: Push the latest Docker image
      run: docker push ghcr.io/manykarim/robotframework-doctestlibrary/rf-doctest:latest
